### ISSUE TITLE
Why total Flops is 273.95MFlops, but Flops of the paper is 167 MFlops

### ISSUE THREAD

**Issue by JasonYangCode** [likyoo/GhostNetV2-PyTorch#1]
Total params: 4,653,040
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total memory: 68.62MB
Total MAdd: 536.85MMAdd
Total Flops: 273.95MFlops
Total MemR+W: 160.61MB

**Comment by likyoo** [comment]
try this: https://github.com/huawei-noah/Efficient-AI-Backbones/tree/master/ghostnetv2_pytorch
